### ISSUE TITLE
Build payload externally

### ISSUE THREAD

**Issue by yurem** [devsu/push-sender#2]
Hi,

Your library provides simple interface to allow easily add push notification support to application.
But PayloadBuilder provides more flexible way to build messages. For example we need to send something like this:
{"aps":{"alert":"Testing..","badge":0,"sound":"default", "category":"ACTIONABLE"}, "request":...

Now it's not possible to specify 'badge' and 'category'.

What do you think about adding methods like this?
public boolean sendPush(PayloadBuilder msgBuilder, String token) throws Exception {..}
or 
public boolean sendPush(String payload, String token) throws Exception {..}

**Comment by rion18** [comment]
This is certainly something to consider. I'll make the changes and post a new version sometime during this week. Thanks for your interest in Push Sender!

**Comment by gchristov** [comment]
Hey, I would also like to request this feature as it's definitely needed. Also currently there doesn't seem to be support for localizing the alert message which is offered by `PayloadBuilder`. Allowing it to build externally would definitely solve both problems.

**Comment by rion18** [comment]
Thanks for your feedback, payloads can now be built externally!
